export const dashboardCopy = {
  eyebrow: {
    en: "Lydia's Dépanneur OS x Enterprise Aero",
    fr: "Lydia's Dépanneur OS x Enterprise Aero",
    "zh-Hans": "Lydia's Dépanneur OS x Enterprise Aero",
    "zh-Hant": "Lydia's Dépanneur OS x Enterprise Aero",
  },
  heroTitle: {
    en: "Maintain infrastructure, and let the revenue follow.",
    fr: "Maintenir l'infrastructure, et laisser le revenu suivre.",
    "zh-Hans": "先稳固基础设施，再让收入跟着来。",
    "zh-Hant": "先穩固基礎設施，再讓收入跟著來。",
  },
  heroBody: {
    en: "Maintenance preserves capital here. Clean presentation, steady cold chains, and a unified data pool ensure operational resilience.",
    fr: "Ici, la maintenance préserve le capital. Une présentation impeccable, une chaîne du froid constante et une base de données unifiée assurent la résilience opérationnelle.",
    "zh-Hans": "在这里，维护能保全资本。整洁的陈列、稳定的冷链加上统一的数据池，才能确保运营韧性。",
    "zh-Hant": "在這裡，維護能保全資本。整潔的陳列、穩定的冷鏈加上統一的資料池，才能確保營運韌性。",
  },
  shiftTitle: {
    en: "System unlocked. Select your role.",
    fr: "Système déverrouillé. Sélectionnez votre rôle.",
    "zh-Hans": "系统已解锁。请选择您的角色。",
    "zh-Hant": "系統已解鎖。請選擇您的角色。",
  },
  shiftBody: {
    en: "Select your profile. This system serves as the unified data pool for standard operating procedures. Ensure clean handoffs and strict data continuity.",
    fr: "Sélectionnez votre profil. Ce système agit comme base de données unifiée pour les procédures d'opération standard. Assurez des transferts propres et une conformité de données stricte.",
    "zh-Hans": "选择身份。此系统作为标准操作程序的统一数据池。确保交接清晰，维持严格的数据连续性。",
    "zh-Hant": "選取身分。此系統作為標準作業程序的統一資料池。確保交接清晰，維持嚴格的資料連續性。",
  },
  switchShift: {
    en: "Switch shift",
    fr: "Changer de quart",
    "zh-Hans": "切换班次",
    "zh-Hant": "切換班次",
  },
  cleanHandoff: {
    en: "Clean handoff ready",
    fr: "Clean handoff prêt",
    "zh-Hans": "清洁交接已就绪",
    "zh-Hant": "清潔交接已就緒",
  },
  moneyQuestion: {
    en: "Step 1: Reconcile Revenue Data.",
    fr: "Étape 1 : Réconciliez les données de revenus.",
    "zh-Hans": "第一步：核对收入数据。",
    "zh-Hant": "第一步：核對收入數據。",
  },
  cashSales: {
    en: "Cash sales",
    fr: "Ventes comptant",
    "zh-Hans": "现金销售",
    "zh-Hant": "現金銷售",
  },
  cardSales: {
    en: "Card sales",
    fr: "Ventes carte",
    "zh-Hans": "刷卡销售",
    "zh-Hant": "刷卡銷售",
  },
  supplierSpend: {
    en: "Supplier spend",
    fr: "Dépenses fournisseurs",
    "zh-Hans": "供货支出",
    "zh-Hant": "供貨支出",
  },
  wageSpend: {
    en: "Wage spend",
    fr: "Salaires",
    "zh-Hans": "工资支出",
    "zh-Hant": "工資支出",
  },
  repairFund: {
    en: "Repair fund",
    fr: "Fonds réparation",
    "zh-Hans": "维修基金",
    "zh-Hant": "維修基金",
  },
  savingsTarget: {
    en: "Savings target",
    fr: "Cible d'épargne",
    "zh-Hans": "储蓄目标",
    "zh-Hant": "儲蓄目標",
  },
  gross: {
    en: "Gross today",
    fr: "Brut aujourd'hui",
    "zh-Hans": "今日总收入",
    "zh-Hant": "今日總收入",
  },
  net: {
    en: "Net after spend",
    fr: "Net après dépenses",
    "zh-Hans": "扣支出后净额",
    "zh-Hant": "扣支出後淨額",
  },
  leak: {
    en: "Leak per day",
    fr: "Fuite par jour",
    "zh-Hans": "每日流失",
    "zh-Hant": "每日流失",
  },
  payback: {
    en: "Theoretical payback",
    fr: "Retour théorique",
    "zh-Hans": "理论回本期",
    "zh-Hant": "理論回本期",
  },
  days: {
    en: "days",
    fr: "jours",
    "zh-Hans": "天",
    "zh-Hant": "天",
  },
  sweepFund: {
    en: "Sweep today's net into the repair fund",
    fr: "Basculer le net du jour dans le fonds réparation",
    "zh-Hans": "把今天净额转入维修基金",
    "zh-Hant": "把今天淨額轉入維修基金",
  },
  prophecyTitle: {
    en: "Risk Mitigation Alert",
    fr: "Alerte de mitigation des risques",
    "zh-Hans": "风险缓释提醒",
    "zh-Hant": "風險緩釋提醒",
  },
  prophecyButton: {
    en: "Next Alert",
    fr: "Alerte suivante",
    "zh-Hans": "下一条提醒",
    "zh-Hant": "下一條提醒",
  },
  openSourcing: {
    en: "Open NDG sourcing",
    fr: "Ouvrir l'approvisionnement NDG",
    "zh-Hans": "打开 NDG 采购",
    "zh-Hant": "打開 NDG 採購",
  },
  keepPush: {
    en: "Push to Google Keep",
    fr: "Pousser vers Google Keep",
    "zh-Hans": "推送到 Google Keep",
    "zh-Hant": "推送到 Google Keep",
  },
  exportCalendar: {
    en: "Export heartbeat calendar",
    fr: "Exporter le calendrier heartbeat",
    "zh-Hans": "导出心跳日历",
    "zh-Hant": "匯出心跳日曆",
  },
  exportBackup: {
    en: "Export JSON backup",
    fr: "Exporter la sauvegarde JSON",
    "zh-Hans": "导出 JSON 备份",
    "zh-Hant": "匯出 JSON 備份",
  },
  importBackup: {
    en: "Import JSON backup",
    fr: "Importer la sauvegarde JSON",
    "zh-Hans": "导入 JSON 备份",
    "zh-Hant": "匯入 JSON 備份",
  },
  sourcingTitle: {
    en: "Smart sourcing agent",
    fr: "Agent d'approvisionnement intelligent",
    "zh-Hans": "智能采购代理",
    "zh-Hant": "智慧採購代理",
  },
  sourcingBody: {
    en: "Think like an ABAP debugger: reset, prove prerequisites, isolate the cheap failing branch, then buy parts before buying labour.",
    fr: "Pensez comme un débogueur ABAP : reset, prérequis, branche fautive la moins chère, puis pièces avant main-d'oeuvre.",
    "zh-Hans": "像 ABAP 调试一样处理：先重置，证明前提，隔离最便宜的故障分支，再先买零件，后买人工。",
    "zh-Hant": "像 ABAP 偵錯一樣處理：先重置，證明前提，隔離最便宜的故障分支，再先買零件，後買人工。",
  },
  runAgent: {
    en: "Run sourcing agent",
    fr: "Lancer l'agent sourcing",
    "zh-Hans": "运行采购代理",
    "zh-Hant": "執行採購代理",
  },
  techQuote: {
    en: "Typical technician quote",
    fr: "Devis technicien typique",
    "zh-Hans": "常见技师报价",
    "zh-Hant": "常見技師報價",
  },
  partsCost: {
    en: "DIY parts cost",
    fr: "Coût pièces DIY",
    "zh-Hans": "DIY 零件成本",
    "zh-Hant": "DIY 零件成本",
  },
  savingsFound: {
    en: "Savings captured",
    fr: "Économies captées",
    "zh-Hans": "已抓住的节省",
    "zh-Hant": "已抓住的節省",
  },
  bookSavings: {
    en: "Book savings into repair fund",
    fr: "Inscrire l'économie dans le fonds réparation",
    "zh-Hans": "把节省记入维修基金",
    "zh-Hant": "把節省記入維修基金",
  },
  localSources: {
    en: "Montreal and NDG counters",
    fr: "Comptoirs Montréal et NDG",
    "zh-Hans": "蒙特利尔和 NDG 柜台",
    "zh-Hant": "蒙特利爾和 NDG 櫃檯",
  },
  onlineSources: {
    en: "Wholesale online backups",
    fr: "Backups grossistes en ligne",
    "zh-Hans": "线上批发备选",
    "zh-Hant": "線上批發備選",
  },
  logicLoop: {
    en: "DIY logic loop",
    fr: "Boucle logique DIY",
    "zh-Hans": "DIY 逻辑回路",
    "zh-Hant": "DIY 邏輯回路",
  },
  likelyParts: {
    en: "Likely parts first",
    fr: "Pièces probables d'abord",
    "zh-Hans": "优先检查可能零件",
    "zh-Hant": "優先檢查可能零件",
  },
  revenueMoves: {
    en: "Revenue protection moves",
    fr: "Gestes de protection du revenu",
    "zh-Hans": "保护收入的动作",
    "zh-Hant": "保護收入的動作",
  },
  escalate: {
    en: "Escalate only when",
    fr: "Escalader seulement si",
    "zh-Hans": "只在这些情况升级",
    "zh-Hant": "只在這些情況升級",
  },
  hopperTitle: {
    en: "The intake hopper",
    fr: "La trémie d'intake",
    "zh-Hans": "混沌录入斗",
    "zh-Hant": "混沌錄入斗",
  },
  hopperBody: {
    en: "Drop in messy notes, voice transcripts, or half-finished thoughts. The parser turns them into structured board updates so nobody has to carry the story in their head.",
    fr: "Déposez des notes sales, des transcriptions ou des pensées incomplètes. Le parseur les transforme en mises à jour structurées du tableau.",
    "zh-Hans": "把凌乱笔记、语音转写或半句想法直接丢进来。解析器会把它们变成结构化更新，不必再靠谁用脑子硬记。",
    "zh-Hant": "把凌亂筆記、語音轉寫或半句想法直接丟進來。解析器會把它們變成結構化更新，不必再靠誰用腦子硬記。",
  },
  hopperPlaceholder: {
    en: "Short 2 cases Molson, need new compressor relay, Pepsi route late, wife logged 4 ice bag holds.",
    fr: "Short 2 caisses Molson, besoin d'un nouveau relais compresseur, route Pepsi en retard, 4 réserves de glace.",
    "zh-Hans": "Molson 少了 2 箱，需要新的压缩机继电器，百事路线延迟，老婆记了 4 个冰袋预留。",
    "zh-Hant": "Molson 少了 2 箱，需要新的壓縮機繼電器，百事路線延遲，老婆記了 4 個冰袋預留。",
  },
  parseHopper: {
    en: "Parse hopper",
    fr: "Parser la trémie",
    "zh-Hans": "解析录入斗",
    "zh-Hant": "解析錄入斗",
  },
  applyHopper: {
    en: "Apply clean handoff",
    fr: "Appliquer le clean handoff",
    "zh-Hans": "应用清洁交接",
    "zh-Hant": "套用清潔交接",
  },
  inventoryTitle: {
    en: "Laptop-ready inventory board",
    fr: "Tableau inventaire pour portable",
    "zh-Hans": "适合笔记本的库存板",
    "zh-Hant": "適合筆電的庫存板",
  },
  search: {
    en: "Search a lane",
    fr: "Chercher une ligne",
    "zh-Hans": "搜索货线",
    "zh-Hant": "搜尋貨線",
  },
  onHand: {
    en: "On hand",
    fr: "En main",
    "zh-Hans": "现有",
    "zh-Hant": "現有",
  },
  parLevel: {
    en: "Par",
    fr: "Niveau cible",
    "zh-Hans": "基准",
    "zh-Hant": "基準",
  },
  unitCost: {
    en: "Unit cost",
    fr: "Coût unitaire",
    "zh-Hans": "单位成本",
    "zh-Hant": "單位成本",
  },
  shelfPrice: {
    en: "Shelf price",
    fr: "Prix rayon",
    "zh-Hans": "货架价",
    "zh-Hant": "貨架價",
  },
  barcode: {
    en: "Barcode",
    fr: "Code-barres",
    "zh-Hans": "条码",
    "zh-Hant": "條碼",
  },
  requestBoard: {
    en: "Special customer requests",
    fr: "Demandes spéciales clients",
    "zh-Hans": "特殊顾客需求",
    "zh-Hant": "特殊顧客需求",
  },
  complianceTitle: {
    en: "Quebec heartbeat and supplier rhythm",
    fr: "Heartbeat Québec et rythme fournisseur",
    "zh-Hans": "魁北克心跳与供货节奏",
    "zh-Hant": "魁北克心跳與供貨節奏",
  },
  markDone: {
    en: "Mark reviewed",
    fr: "Marquer révisé",
    "zh-Hans": "标记已复核",
    "zh-Hant": "標記已複核",
  },
  nextDue: {
    en: "Next due",
    fr: "Prochaine échéance",
    "zh-Hans": "下次到期",
    "zh-Hant": "下次到期",
  },
  supplierRhythm: {
    en: "Supplier rhythm",
    fr: "Rythme fournisseur",
    "zh-Hans": "供货节奏",
    "zh-Hant": "供貨節奏",
  },
  maintenanceQueue: {
    en: "Maintenance queue",
    fr: "File maintenance",
    "zh-Hans": "维修队列",
    "zh-Hant": "維修隊列",
  },
  audioPanel: {
    en: "Persistent soundtrack",
    fr: "Bande-son persistante",
    "zh-Hans": "持续播放的背景音",
    "zh-Hant": "持續播放的背景音",
  },
  play: {
    en: "Play",
    fr: "Lire",
    "zh-Hans": "播放",
    "zh-Hant": "播放",
  },
  pause: {
    en: "Pause",
    fr: "Pause",
    "zh-Hans": "暂停",
    "zh-Hant": "暫停",
  },
  ready: {
    en: "Ready",
    fr: "Prêt",
    "zh-Hans": "就绪",
    "zh-Hant": "就緒",
  },
  issue: {
    en: "Issue",
    fr: "Problème",
    "zh-Hans": "问题",
    "zh-Hant": "問題",
  },
  structuredOutput: {
    en: "Structured output",
    fr: "Sortie structurée",
    "zh-Hans": "结构化输出",
    "zh-Hant": "結構化輸出",
  },
  note: {
    en: "Note",
    fr: "Note",
    "zh-Hans": "备注",
    "zh-Hant": "備註",
  },
  officialLink: {
    en: "Official link",
    fr: "Lien officiel",
    "zh-Hans": "官方链接",
    "zh-Hant": "官方連結",
  },
  ownerCloseout: {
    en: "Lydia owner closeout",
    fr: "Fermeture propriétaire Lydia",
    "zh-Hans": "Lydia 店主收尾",
    "zh-Hant": "Lydia 店主收尾",
  },
  sourcingKeep: {
    en: "Montreal sourcing plan",
    fr: "Plan sourcing Montréal",
    "zh-Hans": "蒙特利尔采购方案",
    "zh-Hant": "蒙特利爾採購方案",
  },
  cleanHandoffTitle: {
    en: "Lydia clean handoff",
    fr: "Clean handoff Lydia",
    "zh-Hans": "Lydia 清洁交接",
    "zh-Hant": "Lydia 清潔交接",
  },
  complianceKeep: {
    en: "Lydia compliance heartbeat",
    fr: "Heartbeat conformité Lydia",
    "zh-Hans": "Lydia 合规心跳",
    "zh-Hant": "Lydia 合規心跳",
  },
  invalidBackup: {
    en: "This backup file could not be read.",
    fr: "Ce fichier de sauvegarde est illisible.",
    "zh-Hans": "这个备份文件无法读取。",
    "zh-Hant": "這個備份檔案無法讀取。",
  },
  working: {
    en: "Working...",
    fr: "Traitement...",
    "zh-Hans": "处理中...",
    "zh-Hant": "處理中...",
  },
  keepReady: {
    en: "Google Keep payload copied. Keep is opening in a new tab.",
    fr: "Le payload Google Keep est copié. Keep s'ouvre dans un nouvel onglet.",
    "zh-Hans": "Google Keep 内容已复制，正在新标签页打开 Keep。",
    "zh-Hant": "Google Keep 內容已複製，正在新分頁打開 Keep。",
  },
  calendarReady: {
    en: "Heartbeat calendar exported.",
    fr: "Calendrier heartbeat exporté.",
    "zh-Hans": "心跳日历已导出。",
    "zh-Hant": "心跳日曆已匯出。",
  },
  backupReady: {
    en: "JSON backup exported.",
    fr: "Sauvegarde JSON exportée.",
    "zh-Hans": "JSON 备份已导出。",
    "zh-Hant": "JSON 備份已匯出。",
  },
  importReady: {
    en: "Backup imported and family data pool restored.",
    fr: "Sauvegarde importée et pool familial restauré.",
    "zh-Hans": "备份已导入，家庭数据池已恢复。",
    "zh-Hant": "備份已匯入，家庭資料池已恢復。",
  },
  rewardSweep: {
    en: "Revenue sweep booked.",
    fr: "Balayage revenu inscrit.",
    "zh-Hans": "收益转存已记账。",
    "zh-Hant": "收益轉存已記帳。",
  },
  rewardSavings: {
    en: "DIY sourcing savings booked.",
    fr: "Économie sourcing DIY inscrite.",
    "zh-Hans": "DIY 采购节省已入账。",
    "zh-Hant": "DIY 採購節省已入帳。",
  },
  rewardHandoff: {
    en: "Clean handoff posted to the shared pool.",
    fr: "Clean handoff envoyé au pool partagé.",
    "zh-Hans": "清洁交接已推入共享数据池。",
    "zh-Hant": "清潔交接已推入共享資料池。",
  },
  noNegativeSweep: {
    en: "Wait for a positive net before sweeping money to repairs.",
    fr: "Attendre un net positif avant de balayer vers les réparations.",
    "zh-Hans": "先等今天净额转正，再往维修基金里转钱。",
    "zh-Hant": "先等今天淨額轉正，再往維修基金裡轉錢。",
  },
  familyNote: {
    en: "Operational resilience improves when the system acts as a reliable single source of truth.",
    fr: "La résilience opérationnelle s'améliore lorsque le système agit comme source unique de vérité absolue.",
    "zh-Hans": "当系统充当可靠的单一事实来源时，运营韧性就会提升。",
    "zh-Hant": "當系統作為可靠的單一事實來源時，營運韌性就會提升。",
  },
} as const;
